//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace twitter.tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("twitter.tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;created_at&quot;:&quot;Sat Jul 06 01:50:20 +0000 2013&quot;,
        ///   &quot;id&quot;:353330038957019137,
        ///   &quot;id_str&quot;:&quot;353330038957019137&quot;,
        ///   &quot;text&quot;:&quot;RT @SalmesCup: Fiesta Time!!! Lo que pase en #Tenerife se queda en #Tenerife ;-)) #SalmesCup2013 http:\/\/t.co\/eOoz9bdES9&quot;,
        ///   &quot;source&quot;:&quot;\u003ca href=\&quot;http:\/\/twitter.com\/#!\/download\/ipad\&quot; rel=\&quot;nofollow\&quot;\u003eTwitter for iPad\u003c\/a\u003e&quot;,
        ///   &quot;truncated&quot;:false,
        ///   &quot;in_reply_to_status_id&quot;:null,
        ///   &quot;in_reply_to_status_id_str&quot;:null,
        ///   &quot;in_reply_to_user_id&quot;:null,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string twittemr_json_stream {
            get {
                return ResourceManager.GetString("twittemr_json_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;statuses&quot;: [
        ///        {
        ///            &quot;metadata&quot;: {
        ///                &quot;result_type&quot;: &quot;recent&quot;,
        ///                &quot;iso_language_code&quot;: &quot;en&quot;
        ///            },
        ///            &quot;created_at&quot;: &quot;Sat Jun 29 18:37:35 +0000 2013&quot;,
        ///            &quot;id&quot;: 351046807712825344,
        ///            &quot;id_str&quot;: &quot;351046807712825344&quot;,
        ///            &quot;text&quot;: &quot;#stormaudit test location&quot;,
        ///            &quot;source&quot;: &quot;\u003ca href=\&quot;http:\/\/twitter.com\/download\/iphone\&quot; rel=\&quot;nofollow\&quot;\u003eTwitter for iPhone\u003c\/a\u003e&quot;,
        ///            &quot;trunc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string twitter_json_location {
            get {
                return ResourceManager.GetString("twitter_json_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;statuses&quot;: [
        ///        {
        ///            &quot;metadata&quot;: {
        ///                &quot;result_type&quot;: &quot;recent&quot;,
        ///                &quot;iso_language_code&quot;: &quot;fr&quot;
        ///            },
        ///            &quot;created_at&quot;: &quot;Sat Jun 29 19:04:46 +0000 2013&quot;,
        ///            &quot;id&quot;: 351053648522002433,
        ///            &quot;id_str&quot;: &quot;351053648522002433&quot;,
        ///            &quot;text&quot;: &quot;#DukeEnergy test no location&quot;,
        ///            &quot;source&quot;: &quot;\u003ca href=\&quot;http:\/\/twitter.com\/download\/iphone\&quot; rel=\&quot;nofollow\&quot;\u003eTwitter for iPhone\u003c\/a\u003e&quot;,
        ///            &quot;tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string twitter_json_nolocation {
            get {
                return ResourceManager.GetString("twitter_json_nolocation", resourceCulture);
            }
        }
    }
}
